Comport:
  input:
    serial-number: "24230303737351707072"
    baudrate: 1000000
    timeout: 1.0

  output:
    serial-number: "1423530383535140E1A0"
    baudrate: 115200
    sketch: "./ino"

Experimental:
  sound-pin: 2
  led-pin: 3
  reward-pin: 4
  response-pin: [6, 7]
  speaker-id: 2

  reward-duration: 0.01
  timeout-duration: 5.0
  flick-duration: 2.0
  go-maximum-duration: 4.
  nogo-maximum-duration: 20.
  decision-duration: 1.0
  led-flick-hz:   [2, 3, 4, 5, 6, 7, 8, 9]
  sound-flick-hz:   [2, 3, 5, 6, 8, 20]
  go-nogo-boundary: 5.5
  go-ratio: 1
  nogo-ratio: 1
  practice-ratio: 1
  test-ratio: 1

  ITI: 5.
  ITI-range: 0
  number-of-trial: 500

Metadata:
  subject: "name-of-subject"
