Comport:
  input:
    serial-number: "24230303737351707072"
    baudrate: 1000000
    timeout: 1.0

  output:
    serial-number: "1423530383535140E1A0"
    baudrate: 115200
    sketch: "./ino"

Experimental:
  sound-pin: 2
  led-pin: 3
  reward-pin: [4, 5]
  response-pin: [6, 7]
  speaker-id: 2

  reward-duration: 0.02
  timeout-duration: 5.0
  flick-duration: 2.0
  maximum-duration: 4.0
  minimum-duration: 2.0
  decision-duration: 2.0
  led-flick-hz:   [2, 9]
  sound-flick-hz:   [2, 4, 5, 6, 7, 8, 9, 20]
  go-nogo-boundary: 5.5
  go-ratio: 1
  nogo-ratio: 1
  visual-ratio: 1
  sound-ratio: 0

  ITI: 5.
  ITI-range: 0
  number-of-trial: 200

Metadata:
  subject: "name-of-subject"
