Comport:
  input:
    serial-number: "24230303737351707072"
    baudrate: 1000000
    timeout: 1.0

  output:
    serial-number: "1423530383535140E1A0"
    baudrate: 115200
    sketch: "./ino"

Experimental:
  sound-pin: 2
  led-pin: 3
  reward-pin: [4, 5]
  response-pin: [6, 7]
  speaker-id: 2

  reward-duration: 0.02
  flick-duration: 2.0
  decision-duration: 1.0
  led-flick-hz:   [3, 4, 5, 6, 7, 8]
  sound-flick-hz:   [2, 4.5, 6.5, 20]
  lr-boundary: 5.5
  left-ratio: 1
  right-ratio: 1
  visual-ratio: 1
  audio-ratio: 1
  audvis-ratio: 1
  train-ratio: 1
  test-ratio: 1

  ITI: 5.
  ITI-range: 2
  number-of-reward: 300

Metadata:
  subject: "name-of-subject"
