Comport:
  input:
    serial-number: "24230303737351707072"
    baudrate: 1000000
    timeout: 1.0

  output:
    serial-number: "1423530383535140E1A0"
    baudrate: 115200
    sketch: "./ino"

Experimental:
  sound-pin: 2
  led-pin: 3
  reward-pin: 4
  speaker-id: 2

  reward-duration: 0.02
  flick-duration: 1.
  led-flick-hz:   [4, 9]
  sound-flick-hz:   [2, 4, 5, 6, 7, 8, 9, 20]
  go-nogo-boundary: 6.5
  go-ratio: 1
  nogo-ratio: 0
  visual-ratio: 1
  sound-ratio: 0

  ITI: 14.0
  ITI-range: 5.
  number-of-trial: 200

Metadata:
  subject: "name-of-subject"
